CREATE OR REPLACE FUNCTION NAGF_BUSCAEAN_BKLGRS_V2 (PNSEQPRODUTO MAP_PRODUTO.SEQPRODUTO%TYPE, PSTIPOCOD VARCHAR2) RETURN VARCHAR2 IS

    VSCODACESSO VARCHAR2(4000);
    VSCODFINAL VARCHAR2(4000);
 BEGIN
    IF PSTIPOCOD = 'E' THEN
     FOR T IN (
         SELECT   A.CODACESSO CODACESSO
         FROM    CONSINCO.MAP_PRODCODIGO A
         WHERE   A.TIPCODIGO IN ('E')
         AND      A.QTDEMBALAGEM = 1
         AND     A.INDUTILVENDA = 'S'
         AND     A.SEQPRODUTO = PNSEQPRODUTO
     )LOOP
          IF LENGTH(VSCODACESSO || T.CODACESSO || ',') <= 4000 THEN
              VSCODACESSO := VSCODACESSO || T.CODACESSO || ',' ;
          ELSE
              EXIT;
          END IF;
     END LOOP;
     IF VSCODACESSO IS NOT NULL THEN
     VSCODFINAL := VSCODACESSO;
     END IF;
 ELSIF PSTIPOCOD = 'B' THEN
       SELECT MAX( SUBSTR(CODACESSO, 0, LENGTH(CODACESSO) -1)) CODACESSO
       INTO VSCODFINAL
       FROM MAP_PRODCODIGO
       WHERE TIPCODIGO = 'B'
       AND QTDEMBALAGEM = 1
       AND INDUTILVENDA = 'S'
       AND SEQPRODUTO = PNSEQPRODUTO;
     
 END IF;
     RETURN(VSCODFINAL);
     
END;
