CREATE OR REPLACE VIEW NAGV_BKLGRS_MENORPROMOCATIVA AS
SELECT DISTINCT 
       CASE WHEN PromocAtivas.ISACTIVE = 'TRUE' AND PromocTodas.ISACTIVE = 'INACTIVE' THEN LPAD(PromocAtivas.CODPROMOC,15,0)||LPAD(PromocAtivas.SKU,10,0)||LPAD(PromocAtivas.STOREREFERENCE,3,0)  ELSE 
                                                                                           LPAD(PromocTodas.CODPROMOC,15,0)|| LPAD(PromocTodas.SKU,10,0)|| LPAD(PromocTodas.STOREREFERENCE,3,0)   END CODUNICO,
       CASE WHEN PromocAtivas.ISACTIVE = 'TRUE' AND PromocTodas.ISACTIVE = 'INACTIVE' THEN PromocAtivas.CODPROMOC     ELSE PromocTodas.CODPROMOC     END CODPROMOC,
       PromocTodas.SKU IDPRODUTO,
       PromocTodas.STOREREFERENCE IDFILIAL,
       CASE WHEN PromocAtivas.ISACTIVE = 'TRUE' AND PromocTodas.ISACTIVE = 'INACTIVE' THEN PromocAtivas.DESCRIPTION   ELSE PromocTodas.DESCRIPTION   END DESCRIPTION,
       CASE WHEN PromocAtivas.ISACTIVE = 'TRUE' AND PromocTodas.ISACTIVE = 'INACTIVE' THEN PromocAtivas.STARTDATETIME ELSE PromocTodas.STARTDATETIME END DTA_INICIO,
       CASE WHEN PromocAtivas.ISACTIVE = 'TRUE' AND PromocTodas.ISACTIVE = 'INACTIVE' THEN PromocAtivas.ENDDATETIME   ELSE PromocTodas.ENDDATETIME   END DTA_FIM,
       CASE WHEN PromocAtivas.ISACTIVE = 'TRUE' AND PromocTodas.ISACTIVE = 'INACTIVE' THEN PromocAtivas.ISACTIVE      ELSE PromocTodas.ISACTIVE      END ISACTIVE,
       CASE WHEN PromocAtivas.ISACTIVE = 'TRUE' AND PromocTodas.ISACTIVE = 'INACTIVE' THEN PromocAtivas.PRICE         ELSE PromocTodas.PRICE         END PRECO_PROMOC

FROM (
    SELECT T.*,
           ROW_NUMBER() OVER (PARTITION BY T.SKU, T.STOREREFERENCE ORDER BY T.PRICE ASC) ODR1
      FROM NAGV_BKLGRS_PROMOCOES_ATIVAS T
) PromocTodas

LEFT JOIN

(
    SELECT T.*,
           ROW_NUMBER() OVER (PARTITION BY T.SKU, T.STOREREFERENCE ORDER BY T.PRICE ASC) ODR2
      FROM NAGV_BKLGRS_PROMOCOES_ATIVAS_ST T
) PromocAtivas ON PromocTodas.SKU = PromocAtivas.SKU AND PromocTodas.STOREREFERENCE = PromocAtivas.STOREREFERENCE AND ODR2 = 1

WHERE ODR1 = 1 AND EXISTS (SELECT 1 FROM NAGV_EMP_ECOMMERCE A WHERE A.NROEMPRESA = PromocAtivas.STOREREFERENCE);
