CREATE OR REPLACE VIEW NAGV_BKLGRS_CATALOGO AS

SELECT /*+OPTIMIZER_FEATURES_ENABLE('11.2.0.4')*/ 
       LPAD(S.SEQPRODUTO,10,0)||LPAD(S.NROEMPRESA,3,0) COD_CATUNICO,
       S.SEQPRODUTO IDPRODUTO,
       S.NROEMPRESA IDFILIAL,
       S.PRECOVALIDNORMAL PRECO,
       fc5estoquedisponivel(S.SEQPRODUTO,S.NROEMPRESA) ESTOQUE,
       CASE WHEN S.STATUSVENDA = 'A' AND P.INDINTEGRAECOMMERCE = 'S' THEN 'S' ELSE 'N' END ISACTIVE

  FROM  MRL_PRODEMPSEG S INNER JOIN MAP_PRODUTO P ON P.SEQPRODUTO = S.SEQPRODUTO
                         

WHERE 1=1

  AND S.QTDEMBALAGEM = 1
  AND S.STATUSVENDA = 'A'
  AND PRECOVALIDNORMAL > 0
  
  AND EXISTS (SELECT 1 FROM NAGV_EMP_ECOMMERCE A WHERE A.NROEMPRESA = S.NROEMPRESA AND A.NROSEGMENTO = S.NROSEGMENTO)
  ;
