CREATE OR REPLACE VIEW NAGV_BKLGRS_CATALOGO AS
SELECT /*+OPTIMIZER_FEATURES_ENABLE('11.2.0.4')*/
       DISTINCT
       LPAD(S.SEQPRODUTO,10,0)||LPAD(S.NROEMPRESA,3,0) COD_CATUNICO,
       S.SEQPRODUTO IDPRODUTO,
       S.NROEMPRESA IDFILIAL,
       S.PRECOVALIDNORMAL PRECO,
       fc5estoquedisponivel(S.SEQPRODUTO,S.NROEMPRESA) ESTOQUE,
       CASE WHEN S.STATUSVENDA = 'A' AND P.INDINTEGRAECOMMERCE = 'S' THEN 'TRUE' ELSE 'FALSE' END ISACTIVE,
       TO_DATE(GREATEST(M.DTAHORULTMOVTOESTQ,
                        CONSINCO.NAGF_BUSCAULTALTPRECO(S.SEQPRODUTO, S.NROEMPRESA, S.NROSEGMENTO, S.QTDEMBALAGEM)
                       ), 'DD/MM/RRRR') DT_ULTIMA_ALTERACAO,
       CASE WHEN C.CATEGORIAN1 = 'HORTIFRUTI' AND NOT EXISTS (SELECT 1 FROM MAP_PRODCODIGO E WHERE E.SEQPRODUTO = S.SEQPRODUTO AND E.TIPCODIGO = 'E') THEN 1
            WHEN C.CATEGORIAN1 IN ('AÇOUGUE', 'PADARIA', 'FRIOS E LATICINIOS')   AND EXISTS (SELECT 1 FROM NAGT_DEPARA_STOCK_IEAP DP WHERE DP.SEQPRODUTO = S.SEQPRODUTO) THEN 1
            ELSE 0 END PERPETUO

  FROM  MRL_PRODEMPSEG S INNER JOIN MAP_PRODUTO P ON P.SEQPRODUTO = S.SEQPRODUTO
                         INNER JOIN MAX_EMPRESA E ON E.NROEMPRESA = S.NROEMPRESA AND S.NROSEGMENTO = E.NROSEGMENTOPRINC
                         INNER JOIN MRL_PRODUTOEMPRESA M ON M.SEQPRODUTO = S.SEQPRODUTO AND M.NROEMPRESA = S.NROEMPRESA
                         INNER JOIN DIM_CATEGORIA@CONSINCODW C ON C.SEQFAMILIA = P.SEQFAMILIA

WHERE 1=1

  AND S.QTDEMBALAGEM = 1
  AND S.STATUSVENDA = 'A'
  AND PRECOVALIDNORMAL > 0

  --AND EXISTS (SELECT 1 FROM NAGV_EMP_ECOMMERCE A WHERE A.NROEMPRESA = S.NROEMPRESA AND A.NROSEGMENTO = S.NROSEGMENTO)
;
