CREATE OR REPLACE VIEW NAGV_BKLGRS_FILIAL AS
       
SELECT NROEMPRESA IDFILIAL, X.FANTASIA NOMEFANTASIA, NULL DATABERTURA,
       CASE WHEN G.LOGRADOURO LIKE 'AV%' THEN 'AVENIDA'
            WHEN G.LOGRADOURO LIKE 'ESTRADA%' THEN 'ESTRADA'
            WHEN G.LOGRADOURO LIKE 'PRACA%' THEN 'PRACA'
            WHEN G.LOGRADOURO LIKE 'RODOVIA%' THEN 'RODOVIA'
            WHEN G.LOGRADOURO LIKE 'VIA%' THEN 'VIA'
              ELSE 'RUA' END TIPOLOGRADOURO,
       G.LOGRADOURO LOGRADOURO,
       G.NROLOGRADOURO NUMNUMERO,
       G.CMPLTOLOGRADOURO COMPLEMENTO,
       G.BAIRRO BAIRRO,
       G.CIDADE CIDADE,
       G.CEP NUMCEP,
       G.UF UF,
       X.LATITUDE NUMLAT,
       X.LONGITUDE NUMLONG,
       TIPO TIPOFILIAL,
       CODREGIONAL IDREGIONAL,
       DESCREGIONAL REGIONAL,
       METRAGEM NUMMETRAGEM,
       AREADEVENDAS NUMAREAVENDA,
       FUNCIONARIOS QTDFUNCIONARIOS,
       'PROPRIA' FRANQUIA,
       DECODE(X.OPERACAOINICIADA, 'S',1,'N',0) FLGATIVA,
       'LOJA' CANALATENDIMENTO,
       CNPJ CPFCNPJ

  FROM DWNAGT_DADOSEMPRESA@BI X INNER JOIN CONSINCO.GE_PESSOA G ON G.SEQPESSOA = X.NROEMPRESA;
