CREATE OR REPLACE VIEW NAGV_BKLGRS_CATALOGO AS
  
SELECT S.SEQPRODUTO IDPRODUTO,
       S.NROEMPRESA IDFILIAL,
       S.PRECOVALIDNORMAL PRECO,
       fc5estoquedisponivel(S.SEQPRODUTO,S.NROEMPRESA) ESTOQUE,
       CASE WHEN S.STATUSVENDA = 'A' AND P.INDINTEGRAECOMMERCE = 'S' THEN 'S' ELSE 'N' END ISACTIVE

  FROM  MRL_PRODEMPSEG S INNER JOIN MAP_PRODUTO P ON P.SEQPRODUTO = S.SEQPRODUTO

WHERE 1=1

  AND S.QTDEMBALAGEM = 1
  AND S.STATUSVENDA = 'A'
  AND S.NROSEGMENTO IN (5,8)
  AND PRECOVALIDNORMAL > 0;
