CREATE OR REPLACE VIEW NAGV_BKLGRS_PRODUTO AS
SELECT X.SEQPRODUTO IDPRODUTO,
       X.DESCCOMPLETA DESCRICAOCOMPLETA,
       REPLACE(X.DESCREDUZIDA, ';',' ') DESCRICAORESUMIDA,
       DECODE(PESAVEL, 'S', 'KG', 'UN') UNIDADE,
       D.DESCRICAO DEPTO,
       C.CATEGORIAN1 CATEGORIA,
       C.CATEGORIAN2 GRUPO,
       C.CATEGORIAN3 SUBGRUPO,
       MARCA MARCA,
       CASE WHEN MARCA = 'NAGUMO' THEN 'S' ELSE 'N' END MARCAPROPRIA,
       CASE WHEN CATEGORIAN1 = 'SAZONALIDADE' THEN 'S' ELSE 'N' END PORDUTOSAZONAL,
       B.SEQPRODUTO IDMATERIALPAI,
       B.DESCCOMPLETA DESCRICAOMATERIALPAI,
       SEQFORNECEDOR IDFORNECEDOR,
       NOMERAZAO NOMEFORNECEDOR,
       NVL(RTRIM(NAGF_BUSCAEAN_CRM(X.SEQPRODUTO), ','), x.SEQPRODUTO) EAN,
       REPLACE(REPLACE(X.NOMEPRODUTOECOMM,CHR(13), ''), CHR(10), '') DESC_HUMANIZADA,
       NVL(X.INDINTEGRAECOMMERCE,'N') IND_INTEGRA_ECOMM

  FROM MAP_PRODUTO X INNER JOIN DIM_CATEGORIA@CONSINCODW C ON C.SEQFAMILIA = X.SEQFAMILIA
                     INNER JOIN MAP_FAMILIA F ON F.SEQFAMILIA = X.SEQFAMILIA
                      LEFT JOIN MAP_MARCA M ON M.SEQMARCA = F.SEQMARCA
                      LEFT JOIN MAP_FAMFORNEC Z ON Z.SEQFAMILIA = X.SEQFAMILIA AND Z.PRINCIPAL = 'S'
                     INNER JOIN GE_PESSOA G ON G.SEQPESSOA = Z.SEQFORNECEDOR
                      LEFT JOIN MAP_PRODUTO B ON B.SEQPRODUTO = X.SEQPRODUTOBASE
                     INNER JOIN MAP_FAMDIVISAO FD ON FD.SEQFAMILIA = X.SEQFAMILIA
                      LEFT JOIN MRL_PRODUTOEMPRESA EM ON EM.SEQPRODUTO = X.SEQPRODUTO AND EM.NROEMPRESA = 8
                      LEFT JOIN MRL_DEPARTAMENTO D ON D.NRODEPARTAMENTO = EM.NRODEPARTAMENTO AND D.NROEMPRESA = EM.NROEMPRESA;
