CREATE OR REPLACE VIEW NAGV_BKLGRS_PRODUTO_V2 AS
SELECT X.SEQPRODUTO IDPRODUTO,
       X.DESCCOMPLETA DESCRICAOCOMPLETA,
       REPLACE(X.DESCREDUZIDA, ';',' ') DESCRICAORESUMIDA,
       DECODE(PESAVEL, 'S', 'KG', 'UN') UNIDADE,
       C.CATEGORIAN1 CATEGORIA,
       C.CATEGORIAN2 GRUPO,
       C.CATEGORIAN3 SUBGRUPO,
       MARCA MARCA,
       CASE WHEN MARCA = 'NAGUMO' THEN 'TRUE' ELSE 'FALSE' END MARCAPROPRIA,
       CASE WHEN CATEGORIAN1 = 'SAZONALIDADE' THEN 'TRUE' ELSE 'FALSE' END PRODUTOSAZONAL,
       B.SEQPRODUTO IDMATERIALPAI,
       B.DESCCOMPLETA DESCRICAOMATERIALPAI,
       SEQFORNECEDOR IDFORNECEDOR,
       NOMERAZAO NOMEFORNECEDOR,
       PC.CODACESSO EAN,
       REPLACE(REPLACE(X.NOMEPRODUTOECOMM,CHR(13), ''), CHR(10), '') DESC_HUMANIZADA,
       CASE WHEN NVL(X.INDINTEGRAECOMMERCE,'N') = 'S' THEN 'TRUE' ELSE 'FALSE' END IND_INTEGRA_ECOMM,
         'https://assetsmn.s3.us-east-1.amazonaws.com/assets/ofertas/'||X.SEQPRODUTO||'.jpg' URL,
       GREATEST(NVL(X.DTAHORINCLUSAO,     SYSDATE - 7), -- Data de Inclusao
                NVL(X.DTAHORALTERACAO,    SYSDATE - 7), -- Data de Alteracao do Prod
                NVL(F.DTAHORALTERACAO,    SYSDATE - 7), -- Data de Alteracao na Familia
                NVL(PC.DATAHORAALTERACAO, SYSDATE - 7)  -- Data de Alteracao no Codigo (EAN)
                )
                DTA_ALT

  FROM MAP_PRODUTO X INNER JOIN DIM_CATEGORIA@CONSINCODW C ON C.SEQFAMILIA = X.SEQFAMILIA
                     INNER JOIN MAP_FAMILIA F ON F.SEQFAMILIA = X.SEQFAMILIA
                      LEFT JOIN MAP_MARCA M ON M.SEQMARCA = F.SEQMARCA
                      LEFT JOIN MAP_FAMFORNEC Z ON Z.SEQFAMILIA = X.SEQFAMILIA AND Z.PRINCIPAL = 'S'
                     INNER JOIN GE_PESSOA G ON G.SEQPESSOA = Z.SEQFORNECEDOR
                      LEFT JOIN MAP_PRODUTO B ON B.SEQPRODUTO = X.SEQPRODUTOBASE
                     INNER JOIN MAP_FAMDIVISAO FD ON FD.SEQFAMILIA = X.SEQFAMILIA
                      LEFT JOIN MAP_PRODCODIGO PC ON PC.SEQPRODUTO = X.SEQPRODUTO AND PC.TIPCODIGO = 'E' AND PC.INDUTILVENDA = 'S';
